shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('greetings/', views.greetings),
    path('', views.list_item, name='list_item'),
    path('<int:item_id>/', views.detail_item, name='detail_item'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

shop/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=30)
    price = models.IntegerField(default=0, null=True)

    def __str__(self):
        return f'{self.name}, {self.price}'


class Purchase(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    date_purchase = models.DateTimeField('date purchase')

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Item, Purchase


def greetings(request):
    return HttpResponse('Добро пожаловать в наш магазин!')


def list_item(request):
    items = Item.objects.all()
    context = {
        'latest_item_list': items
    }
    return render(request, 'list_item.html', context)

def detail_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    context = {'item': item}
    return render(request, 'detail_item.html', context)

shop/templates/detail_item.html
{{ item }}

{% for purchase in item.purchase_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ purchase.name }}</label><br>
    {% endfor %}

shop/templates/list_item.html
{% if latest_item_list %}
    <ul>
    {% for item in latest_item_list %}
        <li><a href="#">{{ item.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}